hospital_name: Hospital_B
host: 127.0.0.1
receive_port: 9102
aggregator_host: 127.0.0.1
aggregator_receive_port: 9202
chunk_size_bytes: 65536
socket_timeout_seconds: 300
connect_retry_attempts: 120
connect_retry_delay_seconds: 1
transfer_log_filename: transfer.log
