hospital_name: Hospital_B
uploads_dir: uploads
models_dir: models
logs_dir: logs
received_global_models_dir: communication/received_global_models
local_updates_dir: communication/local_model_updates
dataset_filename: hospital_b_diabetes.csv
model_filename: hospital_b_diabetes_classifier.pt
training_log_filename: training.log
prediction_log_filename: prediction.log
federated_log_filename: federated_client.log
current_global_model_filename: current_global_model.pt
target_column: Outcome
validation_ratio: 0.25
batch_size: 4
epochs: 80
learning_rate: 0.001
hidden_dim: 16
random_seed: 43
